# Generated by Django 4.1.2 on 2022-10-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Geo",
            fields=[("id", models.AutoField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[("id", models.AutoField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField()),
                ("language", models.CharField(max_length=2)),
                ("source", models.CharField(max_length=140)),
                ("like_count", models.IntegerField()),
                ("quote_count", models.IntegerField()),
                ("reply_count", models.IntegerField()),
                ("retweet_count", models.IntegerField()),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.users"
                    ),
                ),
                (
                    "geo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.geo"
                    ),
                ),
            ],
        ),
    ]
